#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xC36CDCB4DF00C68C (infra-root@openstack.org)
#
Name     : barbican
Version  : 7.0.0
Release  : 8
URL      : https://tarballs.openstack.org/barbican/barbican-7.0.0.tar.gz
Source0  : https://tarballs.openstack.org/barbican/barbican-7.0.0.tar.gz
Source99 : https://tarballs.openstack.org/barbican/barbican-7.0.0.tar.gz.asc
Summary  : OpenStack Secure Key Management
Group    : Development/Tools
License  : Apache-2.0
Requires: barbican-bin = %{version}-%{release}
Requires: barbican-config = %{version}-%{release}
Requires: barbican-license = %{version}-%{release}
Requires: barbican-python = %{version}-%{release}
Requires: barbican-python3 = %{version}-%{release}
Requires: Babel
Requires: Paste
Requires: PasteDeploy
Requires: SQLAlchemy
Requires: WebOb
Requires: alembic
Requires: castellan
Requires: cffi
Requires: cryptography
Requires: eventlet
Requires: jsonschema
Requires: keystonemiddleware
Requires: ldap3
Requires: oslo.config
Requires: oslo.context
Requires: oslo.db
Requires: oslo.i18n
Requires: oslo.log
Requires: oslo.messaging
Requires: oslo.middleware
Requires: oslo.policy
Requires: oslo.serialization
Requires: oslo.service
Requires: oslo.utils
Requires: oslo.versionedobjects
Requires: pbr
Requires: pecan
Requires: pyOpenSSL
Requires: pycrypto
Requires: six
Requires: stevedore
BuildRequires : Mako-python
BuildRequires : SQLAlchemy-python
BuildRequires : Tempita-python
BuildRequires : WebOb-python
BuildRequires : WebTest
BuildRequires : alembic-python
BuildRequires : buildreq-distutils3
BuildRequires : castellan-python
BuildRequires : cliff-python
BuildRequires : cmd2-python
BuildRequires : keystonemiddleware
BuildRequires : ldap3
BuildRequires : logutils-python
BuildRequires : oslo.db-python
BuildRequires : oslo.policy-python
BuildRequires : oslo.versionedobjects-python
BuildRequires : pbr
BuildRequires : pecan-python
BuildRequires : pluggy
BuildRequires : prettytable
BuildRequires : py-python
BuildRequires : pycrypto
BuildRequires : pytest
BuildRequires : python-barbicanclient-python
BuildRequires : python-editor-python
BuildRequires : sqlalchemy-migrate-python
BuildRequires : sqlparse
BuildRequires : stevedore
BuildRequires : tox
BuildRequires : virtualenv

%description
Generic single-database configuration.

%package bin
Summary: bin components for the barbican package.
Group: Binaries
Requires: barbican-config = %{version}-%{release}
Requires: barbican-license = %{version}-%{release}

%description bin
bin components for the barbican package.


%package config
Summary: config components for the barbican package.
Group: Default

%description config
config components for the barbican package.


%package license
Summary: license components for the barbican package.
Group: Default

%description license
license components for the barbican package.


%package python
Summary: python components for the barbican package.
Group: Default
Requires: barbican-python3 = %{version}-%{release}

%description python
python components for the barbican package.


%package python3
Summary: python3 components for the barbican package.
Group: Default
Requires: python3-core

%description python3
python3 components for the barbican package.


%prep
%setup -q -n barbican-7.0.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1551032087
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}/usr/lib/python3.7/site-packages python3 setup.py test || :
%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/barbican
cp LICENSE %{buildroot}/usr/share/package-licenses/barbican/LICENSE
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/barbican-db-manage
/usr/bin/barbican-keystone-listener
/usr/bin/barbican-manage
/usr/bin/barbican-retry
/usr/bin/barbican-worker
/usr/bin/barbican-wsgi-api
/usr/bin/pkcs11-kek-rewrap
/usr/bin/pkcs11-key-generation

%files config
%defattr(-,root,root,-)
%config /usr/etc/barbican/barbican-api-paste.ini

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/barbican/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
